### ISSUE TITLE
Search for Movies

### ISSUE THREAD

**Issue by beetlejays** [beetlejays/capstone-project#10]
## Value proposition

**As a** user 
**I want to** search all popular movies,
**so that** that I check all details of available movies in the database.

## Description

![search-with-button](https://user-images.githubusercontent.com/74057596/175280153-7dbd5226-cad4-48a8-acb0-c867276a2ad2.png)

## Acceptance criteria

- [x] Implement input field
- [x] Input search button
- [x] Implement search functionality

## Complexity

Medium 

## Tasks

- [x] Create branch
- [x] Create input field
- [x] Create footer
- [x] Create search button 
- [x] Create search functionality
