### ISSUE TITLE
Listing of current popular movies

### ISSUE THREAD

**Issue by beetlejays** [beetlejays/capstone-project#2]
## Value proposition

**As a** user,
**I want to view the current popular movies as a scrollable list
**so that** I am able to stay up to date with the current movies.

## Description

![movme-index](https://user-images.githubusercontent.com/74057596/175254871-8dcc9487-6e79-493d-ba22-23fee49c903f.png)

## Acceptance criteria

- [ ] Shows listing of popular movies
- [ ] Titles of Movies are listed
- [ ] Image posters of the movies are viewable
- [ ] Page is scrollable

## Complexity

Medium 

## Tasks

- [ ] Create branch
- [ ] Create basic responsive page layout
- [ ] Fetch Data from API
- [ ] Show movie titles
- [ ] Show movie posters
- [ ] Check a11y
