### ISSUE TITLE
Details Page

### ISSUE THREAD

**Issue by beetlejays** [beetlejays/capstone-project#6]
## Value proposition

**As a** user I would like to navigate to a details page of a movie.
**I want to** find out more what the movie is about
**so that** that I can see, if it interests me.

## Description

<img src=xxx.png width=320px>

## Acceptance criteria

- [ ] On tapping of the movie - switch to a details page
- [ ] More details of the movie are viewable

## Complexity

Medium 

## Tasks

- [ ] Create branch
- [ ] Create details page layout
- [ ] Click functionality on movie thumbnail on index
- [ ] Routing to details pages

**Comment by mbosselmann** [comment]
Hi Jay,
good job! 👍 I only have two nit-picking remarks for you to consider:
- **value proposition**: "so **that that** I can view what the movie is about." Only one "that" is needed.
- I think it would be good to describe in your **acceptance criteria** that a **back button** is needed to return to the previous page

Happy hacking :)

**Comment by beetlejays** [comment]
Thanks for the review - will do! ;)
